### ISSUE TITLE
If possible, we should preserve git history in this repo

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ipfs-posinfo#1]
See: https://github.com/libp2p/go-libp2p#modularizing-go-libp2p

**Comment by hacdias** [comment]
This repository is no longer maintained and has been copied over to [Boxo](https://github.com/ipfs/boxo). We are now in the process of reviewing issues and PRs and moving the ones that are still relevant. This issue is no longer relevant, and therefore is being closed.
